### PR TITLE
Add user's location to map and map legend

### LINKED ISSUE #41: Show user's position on map
Use browser APIs

### LINKED ISSUE #42: Marker SVGs Not Appearing
Just need to update linking to where the file is in `feedscript.js`!

### PR DESCRIPTION
**Pull request by mirrorkeydev**
#### Add user's location to map
Adds the user's location to the map as a blue circle marker! Asks for location permissions using the browser. If the user declines to give their location, then the user just isn't added to the map. Resolves #41. In adding the blue marker, I noticed the file paths for the other markers hadn't been updated since the file restructuring, so I went ahead and updated those as well (resolves #42).

image

#### Add map legend
Clicking on the 'legend' button on the map toggles a little legend on top of the map. The positioning on the map allows us to add further buttons later to allow for filtering or other map settings. 

This button presented a keyboard-accessibility issue (only need to read on if you're interested in the details). The premise was that tabbing onto the button (which enables :focus) should change its border to black, and hovering on it (enables :hover) should change the background color to grey. However, this is complicated by the fact that clicking on a button enables :focus on that button until you click somewhere else, which makes the button look "stuck" with a black border for as long as that mouse-user is toggling the legend (not ideal). Much thanks to [this stackoverflow post](https://stackoverflow.com/questions/45093754/anchor-tag-has-focus-style-applied-on-click) for the solution I ended up implementing.

image
image

### CODE REVIEW

**Comment by mirrorkeydev** [comment]
@areetaw I could certainly make it bigger! I wasn't sure if users were wanting to look at it while using the map vs. only opening it once, getting all the infos, and then returning to the map, so I previously settled on putting it off to the side like the built-in map's buttons. It does look a little weird on mobile though. What do you mean by 'making it ... on the actual map'?

**Comment by areetaw** [comment]
> @areetaw I could certainly make it bigger! I wasn't sure if users were wanting to look at it while using the map vs. only opening it once, getting all the infos, and then returning to the map, so I previously settled on putting it off to the side like the built-in map's buttons. It does look a little weird on mobile though. What do you mean by 'making it ... on the actual map'?

Ok, sounds good! For making it on an actual map, I meant including the button on the map, rather than on top of the map; not sure if it's possible though!

**Comment by mirrorkeydev** [comment]
Oh wait were you referring to the button this whole time? As in, the button looks awkward, not the legend itself?

**Comment by areetaw** [comment]
> Oh wait were you referring to the button this whole time? As in, the button looks awkward, not the legend itself?
> 
> Cause I could definitely move the button to the map! :)

Yes, I meant the button! Sorry for not being clear!

**Pull request merged**
